name: cat_breeds
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.5.4
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.6.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  go_router: ^15.2.4
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.15

flutter_native_splash:
  android: true
  ios: true
  image: "assets/cat_breeds.png"
  color: "#a6a6a6"

  android_12:
    image: "assets/cat_breeds.png"
    color: "#a6a6a6"

flutter:
  uses-material-design: true

  assets:
    - .env
    - "assets/cat_breeds.png"
